#!/usr/sh

# system
alias stdown='systemctl poweroff -i'
alias rboot='systemctl reboot -i'
alias lock='swaylock $XDG_CONFIG_HOME/.config/swaylock/config'
alias update='pacman -Syu'

#tdlr
alias '?'='tldr'
alias '??'='man'

# eza
alias ls='eza'
alias lsa='eza -la '
alias lsat='eza -la --tree '

# nvim
alias nv='nvim'
alias vim='nvim'

# bat
alias cat='bat --paging=never --theme=TwoDark'

# grep
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias diff='diff --color=auto'

#yt-dlp
alias yt="yt-dlp -f 'bv[height=1080][ext=mp4]+ba'"

# files
alias cp="cp -vi"
alias mv="mv -vi"
alias rm="rm -vi"
alias del="shred -uv"

#  system adm
alias gpu='nvtop'
alias cpu='btop'

# sudo not required for some system commands
for command in mount umount sv pacman updatedb su shutdown poweroff reboot ; do
  alias $command="sudo $command"
done; unset command
